---
- name: install apache
  become: yes
  hosts: all
  vars_files:
    - vars.yaml
  tasks:
    - name: fail for unsupported os families
      ansible.builtin.fail:
        msg: "This playbook is designed only for RedHat and Debain os families"
      when: ansible_facts['os_family'] != 'RedHat' and ansible_facts['os_family'] != 'Debian'
    - name: install httpd
      package:
        name: "{{ package_name }}"
        state: present
    - name: enable and start httpd
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
