---
- name: install lamp stack
  hosts: webserver
  become: yes
  tasks:
    - name: fail for unsupported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: update packages and install apache2
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present
      notify:
        - enable and start apache 
    - name: install php packages
      ansible.builtin.apt:
        name: "{{ php_packages }}"
        state: present
      notify:
        - restart apache
    - name: copy info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
        remote_src: no
      notify:
        - restart apache
  handlers:
    - name: enable and start apache
      service:
        name: "{{ package }}"
        enabled: yes
        state: started
    - name: restart apache
      service:
        name: "{{ package }}"
        state: restarted


linux, apache, mysql, php

-100 servers

tasks:
 - name: install some {{ webserver }}
    apt:
     - name: "{{ package }}"
       state: present
       100 servers
 - name: install some {{ webserver }}
    service:
     - name: "{{ package }}"
       state: present
       
inventory.yaml
[webserver]
ip package=apache2

2
vars.yaml
---
package: apache2

3
group_vars

all.yaml
---
packages: apache
mysql_version: 1.39

rds: 24.37

webserver
package: apache
         
       
















