---
- name: install nginx server
  hosts: all
  become: yes
  tasks:
    - name: install nginx using apt
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
        state: present
    - name: install nginx using apt
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install nginx using apt
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
      
